#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Input\InputArgument;

require 'vendor/autoload.php';

require 'app.php';

$app = new Application('Hack VM Translator', '1.0');

$app->register('compile')
	->setDescription('Compiles a VM Code to Hack machine language')
	->addArgument('file', InputArgument::REQUIRED, 'file/directory name')
	->setCode( function(InputInterface $input, OutputInterface $output) {

		// to do: the application code ^^

		$fileName = $input->getArgument('file');

		compile($fileName);

		$output->writeln($fileName);
		
		// $name = $input->getArgument('name');
		// $output->writeln('<comment>Hello, ' . $name . '</comment>');
	});

$app->run();